<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'description',
'name',
'layer_group',
'is_visible',
'status',
'sl_no',
'sub_group',
'geom_type',
'info_group',
'minzoom',
'maxzoom',
'sld_name' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'description' => array( 'import_field1' ),
'name' => array( 'import_field2' ),
'layer_group' => array( 'import_field6' ),
'is_visible' => array( 'import_field7' ),
'status' => array( 'import_field8' ),
'sl_no' => array( 'import_field9' ),
'sub_group' => array( 'import_field' ),
'geom_type' => array( 'import_field3' ),
'info_group' => array( 'import_field4' ),
'minzoom' => array( 'import_field5' ),
'maxzoom' => array( 'import_field10' ),
'sld_name' => array( 'import_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field',
'import_field3',
'import_field4',
'import_field5',
'import_field10',
'import_field11' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field',
'import_field3',
'import_field4',
'import_field5',
'import_field10',
'import_field11' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field',
'import_field3',
'import_field4',
'import_field5',
'import_field10',
'import_field11' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'description',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'name',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'layer_group',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'is_visible',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'status',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'sl_no',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'sub_group',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'geom_type',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'info_group',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'minzoom',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'maxzoom',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'sld_name',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 7 );
		?>