version: '3.8'

services:
  tomcat:
    image: tomcat:9.0.108-jdk17-temurin-noble
    container_name: tomcat
    ports:
      - "8082:8080"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    restart: unless-stopped
    networks:
      - shared_net      
networks:
  shared_net:
    external: true    