services:
  pg11db:
    image: postgres:11
    container_name: pg11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db11_data:/var/lib/postgresql/data
    ports:
      - "7032:5432"
    networks:
      - shared_net     
volumes:
  db11_data:

networks:
  shared_net:
    external: true