services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mnzryv
      POSTGRES_DB: postgres
    ports:
      - "6432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/backup                  # <-- add this line
      - ./db/initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_net

volumes:
  db_data:
  # pgadmin_data:
networks:
  shared_net:
    external: true